name: C0RIPG tests

on:
  pull_request:
    branches:
      - main

jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    container: dolfinx/dolfinx:latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: python3 -m pip install pandas

      - name: Run MMS example
        run: python3 velocity-mms.py

